### ISSUE TITLE
Provide unminified code in npm package

### ISSUE THREAD

**Issue by jdalton** [nirgit/simple-xml-to-json#45]
Looking at the project it only sends the minified code to the npm package. To help inspectability and debug using the non-minified source for npm would be helpful. If folks want to bundle it into their projects then they can do so with their method of choice. 

Is the minified form any faster than the non minified?

**Comment by nirgit** [comment]
thank you @jdalton for the feedback. much appreciated. 
to address your comments:
1. re the inspectability & debug issue - this is a valid point, and i'll try to look into it. 
2. re minified code's perf - the tl;dr is that "yes, minified code is faster". 
the reason is mainly due to the fact that because it's smaller, the JS parser has less work to do. 
That said, during execution time this can vary as JS engines tend to be highly optimized these days, which might render the difference in execution time to something quite marginal.

**Comment by nirgit** [comment]
FYI @jdalton.
you can now debug the library's code if you need to starting version 1.2.2
see how on #46

**Comment by jdalton** [comment]
Thank you @nirgit!
